import './globals.css'
import type { Metadata } from 'next'
import Header from './header'
import Footer from './footer'

export const metadata: Metadata = {
  title: 'Gamepity',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
