import './globals.css'
import type { Metadata } from 'next'
import { Playfair_Display } from 'next/font/google'
import Header from './header'
import Footer from './footer'

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Gamepity',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja' className={playfairDisplay.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
